// Code generated by MockGen. DO NOT EDIT.
// Source: page_detail/presenter/rest_handler.go

package mock_presenter

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockRestHandler is a mock of RestHandler interface
type MockRestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRestHandlerMockRecorder
}

// MockRestHandlerMockRecorder is the mock recorder for MockRestHandler
type MockRestHandlerMockRecorder struct {
	mock *MockRestHandler
}

// NewMockRestHandler creates a new mock instance
func NewMockRestHandler(ctrl *gomock.Controller) *MockRestHandler {
	mock := &MockRestHandler{ctrl: ctrl}
	mock.recorder = &MockRestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockRestHandler) EXPECT() *MockRestHandlerMockRecorder {
	return _m.recorder
}

// HandlerGetPageSpecificDetail mocks base method
func (_m *MockRestHandler) HandlerGetPageSpecificDetail(w http.ResponseWriter, r *http.Request) {
	_m.ctrl.Call(_m, "HandlerGetPageSpecificDetail", w, r)
}

// HandlerGetPageSpecificDetail indicates an expected call of HandlerGetPageSpecificDetail
func (_mr *MockRestHandlerMockRecorder) HandlerGetPageSpecificDetail(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "HandlerGetPageSpecificDetail", reflect.TypeOf((*MockRestHandler)(nil).HandlerGetPageSpecificDetail), arg0, arg1)
}
